nn_cfg:
  lr: 1e-4
  method: adam
  intermediate_layer_sizes: [500, 500, 500]
  batch_size: 50
  epochs: 500
  decay_lr: .5
  min_lr: 1e-7
  decay_every: 2000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 2

data:
  datetime: 2022-11-24/10-18-39
  #2022-11-22/08-46-23
  #2022-11-21/22-07-03
  #2022-11-14/15-39-12
  #2022-11-15/20-09-55

train_unrolls: 15
eval_unrolls: 2500
eval_every_x_epochs: 5
N_train: 10000
N_test: 1000
num_samples: 900
prediction_variable: w