nn_cfg:
  lr: 1e-4
  method: adam
  intermediate_layer_sizes: [500, 500, 500]
  batch_size: 50
  epochs: 500
  decay_lr: .5
  min_lr: 1e-7
  decay_every: 2000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 2

data:
  datetime: ''

train_unrolls: 15
eval_unrolls: 2500
eval_every_x_epochs: 40
N_train: 100
N_test: 20
num_samples: 3
prediction_variable: w