nn_cfg:
  lr: 1e-4
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 50
  epochs: 200
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 5000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 2

data:
  datetime: '' #'2022-12-07/00-11-31'

# a: 3000
train_unrolls: 15
eval_unrolls: 500
eval_every_x_epochs: 20
N_train: 100
N_test: 20
num_samples: 20
prediction_variable: w
