# # a: 3000 # 3000 for nasdaq, 2342 for yahoo
# # a: 2380
# a: 3000
# N_train: 1000
# N_test: 20
# # mult_factor: 1000
# # std_mult: 1e-3 #.3
# pen_rets_min: -1.5 #-1.5
# pen_rets_max: -1.5 #-1.5
# # max_clip: 3e-3 #1
# # min_clip: -3e-3 #-1
# solve_acc: 1e-3
# data: 'eod' #'eod' #'yahoo' #'nasdaq'
# alpha: .024
# scale_factor: 1e2
# idio_risk: 1e-3
# noise_var: .02

a: 3000 #2380
N_train: 100
N_test: 20
pen_rets_min: -2
pen_rets_max: -2
solve_acc: 0.001
data: wiki
alpha: 0.024
scale_factor: 100.0
idio_risk: 0.005
noise_var: .02