nn_cfg:
  lr: 1e-3 
  method: adam
  intermediate_layer_sizes: [500, 500, 500]
  batch_size: 50
  epochs: 1
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 5000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 2

data:
  datetime: '' #'2022-12-07/00-11-31'

a: 3000
train_unrolls: 5
eval_unrolls: 500
eval_every_x_epochs: 3
N_train: 10
N_test: 10
num_samples: 9
prediction_variable: w
