nn_cfg:
  lr: 1e-5 
  method: adam
  intermediate_layer_sizes: [500, 500, 500]
  batch_size: 50
  epochs: 500
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 5000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 2

data:
  datetime: ''

a: 3000
train_unrolls: 15
eval_unrolls: 500
eval_every_x_epochs: 3
N_train: 100
N_test: 20
num_samples: 19
prediction_variable: w
